"""fifth

Revision ID: 909165c15c9e
Revises: f445a58cc077
Create Date: 2021-05-12 21:29:31.296262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909165c15c9e'
down_revision = 'f445a58cc077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
