"""third

Revision ID: c95332b171a2
Revises: b38f2c0c2f50
Create Date: 2021-05-10 14:02:44.817321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c95332b171a2"
down_revision = "b38f2c0c2f50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
