"""forth

Revision ID: f445a58cc077
Revises: c95332b171a2
Create Date: 2021-05-10 14:14:40.463702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f445a58cc077"
down_revision = "c95332b171a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
